name: Build and Push Go Binary to S3

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # Change this to your desired Go version

    - name: "Go to Main Folder"
      run: "cd cmd/server"

    - name: Build Go Binary
      run: go build -o myapp

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Upload Binary to S3
      run: |
        aws s3 cp myapp s3://shorturl-binaries/myapp
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
